### ISSUE TITLE
Tiny bug/typo in options setting

### ISSUE THREAD

**Issue by djcoin** [pkrumins/node-lazy#18]
I was checking out your code when I saw a small typo:
https://github.com/pkrumins/node-lazy/blob/master/lazy.js#L21

var endName = opts.pipe || 'end'; 

I guess, it should rather be opts.end.

Cheers,
Simon

**Comment by pkrumins** [comment]
good catch!

**Comment by aikomastboom** [comment]
+1

**Comment by pkrumins** [comment]
fixed!
