### ISSUE TITLE
need to be a stream

### ISSUE THREAD

**Issue by heycalmdown** [pkrumins/node-lazy#20]
Why Lazy is not a Stream but EventEmitter?

**Comment by pkrumins** [comment]
I think because when it was written there wasn't a Stream class.

**Comment by heycalmdown** [comment]
Oh I get it, thanks. So there are no reason for being a stream, then someday it could be. right?

**Comment by rdner** [comment]
I think it will be awesome to use Lazy with Stream and work with chunks as with array items and have ability to pipe to Lazy or from it.
