### ISSUE TITLE
There should be a toArray method

### ISSUE THREAD

**Issue by phihag** [pkrumins/node-lazy#22]
Unfortunately, not every interface supports generators. There should be a method `toArray`, equivalent to this helper:

```
function toArray(Lazy) {
  var res = [];
  Lazy.forEach(function(e) {
    res.push(e);
  });
  return res;
}
```

Or am I just missing an obvious application of an existing method to achieve the same result?

**Comment by nicogranelli** [comment]
I was looking for the same, and I found this: 

``` javascript
lazy.join(function(arr){
  //arr is an array with all the elements
})
```

**Comment by phihag** [comment]
Yup, that's it; `join` is exactly what I'm looking for. Thanks!
