### ISSUE TITLE
Version 1.0.8 no longer in NPMJS repo

### ISSUE THREAD

**Issue by mrsimonemms** [pkrumins/node-lazy#34]
Hi there

We're using Lazy v1.0.8 on a production system.  It appears, since the commit to version 1.0.9 11 days ago that the NPM cannot access v1.0.8.

Can you create tags for all versions so they persist forever?

S

**Comment by pkrumins** [comment]
I'm going to attempt to unpublish lazy@1.0.8, and publish it again.

**Comment by pkrumins** [comment]
I've made a terrible mistake earlier when I published lazy@2.0.0 and realized it doesn't have to be 2.0.0. I accidentally ran `npm -f unpublish lazy` instaead of `npm -f unpublish lazy@2.0.0` so all the lazy versions are gone from npm.

**Comment by pkrumins** [comment]
Now I don't really know what to do because I forgot to tag the versions. I can re-create 1.0.8 because it was the one before the last update, but 1.0.0 - 1.0.7 are gone I'm afraid.

**Comment by pkrumins** [comment]
1.0.8 is now back in npm! Sorry about this. I made a mistake and I should've been more careful. Please confirm that it works for you and I'll close the issue. I'll start tagging releases from now on github.

**Comment by mbrevoort** [comment]
thanks :)

**Comment by mrsimonemms** [comment]
Right, we're mostly winning.  Both v1.0.8 and v1.0.9 are published (thanks), however 1.0.8 is marked at the latest version.  I assume you want v1.0.9 as the latest.

Have a look at the JSON in https://registry.npmjs.org/lazy/ - should explain things a little easier.

**Comment by sergeyksv** [comment]
Can you please make 1.0.9 marked as latest in npmjs because this breaks packages that depend on it when running on node v10.

**Comment by pkrumins** [comment]
Yes of course I can do that. I'm trying to figure out how right now.

**Comment by pkrumins** [comment]
Okay, I just simply did `npm unpublish lazy@1.0.9`, `npm unpublish lazy@1.0.8`, and then `npm publish` both versions in order! Everything looks good now, and I'm closing the issue.

**Comment by mrsimonemms** [comment]
All tested from our end - thanks very much
