### ISSUE TITLE
Misleading example in readme?

### ISSUE THREAD

**Issue by gsf** [pkrumins/node-lazy#8]
The readme.txt shows the following example:

```
var spawn = require('child_process').spawn;
var iptables = spawn('iptables', ['-L', '-n', '-v']);

lazy(iptables.stdout)
    .lines
...
```

When I try something similar, however, I get "TypeError: object is not a function". I believe the emitter needs to be passed to the lazy object at initiation, so something like this instead:

```
var spawn = require('child_process').spawn;
var iptables = spawn('iptables', ['-L', '-n', '-v']);
var lazy = new Lazy(iptables.stdout);

lazy
    .lines
...
```

**Comment by pkrumins** [comment]
I amde a typo. It should be:

Lazy(iptables.stdout)
  .lines

cause Lazy(x) does new Lazy(x) if it's called without new.

but your correction also works.

On 9/4/11, gsf reply@reply.github.com
wrote:

> The readme.txt shows the following example:
> 
> ```
> var spawn = require('child_process').spawn;
> var iptables = spawn('iptables', ['-L', '-n', '-v']);
> 
> lazy(iptables.stdout)
>     .lines
> ...
> ```
> 
> When I try something similar, however, I get "TypeError: object is not a
> function". I believe the emitter needs to be passed to the lazy object at
> initiation, so something like this instead:
> 
> ```
> var spawn = require('child_process').spawn;
> var iptables = spawn('iptables', ['-L', '-n', '-v']);
> var lazy = new Lazy(iptables.stdout);
> 
> lazy
>     .lines
> ...
> ```
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pkrumins/node-lazy/issues/8

## 

P.Krumins
http://www.catonmat.net

**Comment by pkrumins** [comment]
It should totally work:

https://github.com/pkrumins/node-iptables/blob/master/index.js#L30

**Comment by gsf** [comment]
It will work if the require is lowercased as it is in node-iptables:

```
var lazy = require('lazy');
```

One following the readme, however, might think it's the same as the preceding example:

```
var Lazy = require('lazy');
var lazy = new Lazy;
```

In that case, it won't work. I'd say either include the lowercase require, capitalize the `Lazy(iptables.stdout)` line, or change it as I suggested above.

**Comment by pkrumins** [comment]
Nice finding. I didn't realize that was the case. I am gonna update readme right now. Pushing in 5 minutes! Thanks!

**Comment by pkrumins** [comment]
Just pushed! :)
